export default {
  WELCOME: 'Welcome',

  COMMON: {
    MAKE_PHOTO: 'Make photo from camera',
    CHOOSE_PHOTO: 'Choose photo from gallery',
    UPLOAD_PHOTO: 'Upload image',
    CHANGE_PHOTO: 'Change photo',
  },

  LOGIN: {
    TITLE: 'Sign in with account',
    EMAIL_LABEL: 'Email',
    EMAIL_PLACEHOLDER: 'Your email',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: 'Your password',
    FORGOT_PASSWORD: 'Forgot your password?',
    LOGIN: 'Sign in',
    GO_TO_REGISTER: 'Sign up',
    CHANGE_LANGUAGE: 'Change language',
  },

  REGISTER: {
    TITLE: 'Create new account',
    FIRSTNAME_LABEL: 'Firstname',
    FIRSTNAME_PLACEHOLDER: 'Enter your firstname',
    LASTNAME_LABEL: 'Lastname',
    LASTNAME_PLACEHOLDER: 'Enter your lastname',
    LOGIN_LABEL: 'Login',
    LOGIN_PLACEHOLDER: 'Your login',
    NAME_LABEL: 'Name',
    NAME_PLACEHOLDER: 'Your name',
    EMAIL_LABEL: 'Email',
    EMAIL_PLACEHOLDER: 'Your email',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: 'Your password',
    CONFIRM_PASSWORD_LABEL: 'Password confirmation',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Please confirm your password',
    FORGOT_PASSWORD: 'Forgot your password?',
    REGISTER: 'Sign up',
    NO_ACCOUNT: "Don't have an account?",
    GO_TO_LOGIN: 'Go to sign in',
    CHANGE_LANGUAGE: 'Change language',
  },

  RESTORE_PASSWORD: {
    TITLE: 'Search account',
    DESCRIPTION: 'Enter your email address associated with your account',
    MAIL_SENDED:
      'An email was sent to the address associated with your account message. Check your email to continue.',
    EMAIL_LABEL: 'Email',
    EMAIL_PLACEHOLDER: 'Your email',
    RESTORE: 'Restore account',
    SEND_MAIL: 'Send',
    GO_TO_LOGIN: 'Go to sign in',
    HEADER_TITLE: 'Change password',
    RESET_HEADER_TITLE: 'Reset password',
    CURRENT_PASSWORD_LABEL: 'Current password',
    CURRENT_PASSWORD_PLACEHOLDER: 'Your current password',
    NEW_PASSWORD_LABEL: 'New password',
    NEW_PASSWORD_PLACEHOLDER: 'Your new password',
    NEW_PASSWORD_CONFIRM_LABEL: 'Password confirmation',
    NEW_PASSWORD_CONFIRM_PLACEHOLDER: 'Please confirm your password',
    FORGOT_PASSWORD: 'Forgot your password?',
    CHANGE_PASSWORD_BTN: 'Change password',
    RESET_PASSWORD_BTN: 'Save',
  },

  SETTINGS: {
    SUBMIT: 'Submit',
    CHANGE_LANGUAGE: 'Change language',
  },

  EXIT: {
    TITLE: 'Exit',
    SUBTITLE: 'Are you sure you want to quit?',
    CANCEL: 'Cancel',
    OK: 'Ok',
  },

  MODAL: {
    CANCEL: 'Cancel',
    SAVE: 'Save',
    OK: 'Ok',
  },

  BOTTOM_TABS: {
    SEARCH: 'Search',
    ANKETA: 'Anketa',
    PROFILE: 'Profile',
  },

  PROFILE: {
    HEADER_TITLE: 'Profile settings',
    CHANGE_NAME: 'Name',
    CHANGE_EMAIL: 'Email',
    CHANGE_PASSWORD: 'Password',
    CHANGE_LANGUAGE: 'Language',
    CHANGE_AGE: 'Age',
    CHANGE_DATE_BIRTH: 'Birthday',
    CHANGE_SEX: 'Gender',
    CHANGE_CITY: 'City',
    MODAL_TITLE_NAME: 'Name',
    MODAL_PLACEHOLDER_NAME: 'Your name',
    MODAL_TITLE_EMAIL: 'Email',
    MODAL_PLACEHOLDER_EMAIL: 'Your email',
    LOGOUT: 'Logout',
  },

  ANKETA: {
    HEADER_TITLE: 'My anket',
    SMOKING: 'Smoking',
    RELIGION: 'Religion',
    CHILDREN: 'Children',
    HAIR_COLOR: 'Hair color',
    EYE_COLOR: 'Eye color',
    ZODIAC: 'Zodiac sign',
    BODY_TYPE: 'Body type',
    BODY_HEIGHT: 'Height',
    AGE: 'Age',
    SOCIAL_STATUS: 'Social_status',
    BAD_HABITS: 'Attitude towards bad habits',
    WORK_TYPE: 'My occupation',
    MONTHLY_INCOME: 'Monthly income ($)',
    HOBBIES: 'Hobbies',
    MARRIAGE: 'Attitude towards marriage',
    FUTURE_CHILDREN: 'Attitude towards future children',
    POSSESSIONS: 'Material possessions',
    RESPONSIBILITY: 'Attitude towards family responsibilities',
    PLACE_WANT_LIVE: 'I want to live in',
    LEISURE_ACTIVITIES: 'Leisure activities',
    PRESENTS: 'Attitude towards gifts and presents',
    HATES: 'I hate with a passion',
  },

  BIRTHDAY: {
    HEADER_TITLE: 'Change birthday',
    SAVE_BTN: 'Save',
  },
  MODAL_UNSAVED: {
    TITLE: 'Unsaved changes',
    DESCRIPTION: 'You have unsaved changes. Anyway continue?',
    OK_BTN: 'Yes',
    NO_BTN: 'No',
  },
};
