export default {
  WELCOME: 'Welcome',

  ERRORS: {
    INTERNAL_SERVER_ERROR: 'Ошибка сервера',
  },

  COMMON: {
    MAKE_PHOTO: 'Открыть камеру',
    CHOOSE_PHOTO: 'Выбрать из галереи',
    UPLOAD_PHOTO: 'Загрузить фотографию',
    CHANGE_PHOTO: 'Изменить фотографию',
    ADD: 'Добавить',
  },

  LOGIN: {
    TITLE: 'Войти в свой аккаунт',
    EMAIL_LABEL: 'Почта',
    EMAIL_PLACEHOLDER: 'Ваш электронный адрес',
    PASSWORD_LABEL: 'Пароль',
    PASSWORD_PLACEHOLDER: 'Ваш пароль',
    FORGOT_PASSWORD: 'Забыли пароль?',
    LOGIN: 'Войти',
    GO_TO_REGISTER: 'Создать новый аккаунт',
    CHANGE_LANGUAGE: 'Сменить язык',
  },

  REGISTER: {
    TITLE: 'Создать новый аккаунт',
    FIRSTNAME_LABEL: 'Имя',
    FIRSTNAME_PLACEHOLDER: 'Введите свое имя',
    LASTNAME_LABEL: 'Фамилия',
    LASTNAME_PLACEHOLDER: 'Введите свою фамилию',
    LOGIN_LABEL: 'Логин',
    LOGIN_PLACEHOLDER: 'Ваш логин',
    NAME_LABEL: 'Имя',
    NAME_PLACEHOLDER: 'Ваше имя',
    EMAIL_LABEL: 'Почта',
    EMAIL_PLACEHOLDER: 'Ваш электронный адрес',
    PASSWORD_LABEL: 'Пароль',
    PASSWORD_PLACEHOLDER: 'Ваш пароль',
    CONFIRM_PASSWORD_LABEL: 'Подтверждение пароля',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Повторите пароль пожалуйста',
    FORGOT_PASSWORD: 'Забыли пароль?',
    REGISTER: 'Зарегистрироваться',
    NO_ACCOUNT: 'Нет учетной записи?',
    GO_TO_LOGIN: 'Войти в аккаунт',
    CHANGE_LANGUAGE: 'Сменить язык',
    SUCCESSFULLY: 'Поздравляем, вы успешно зарегистрировались! Пожалуйста авторизируйтесь',
  },

  RESTORE_PASSWORD: {
    TITLE: 'Поиск аккаунта',
    DESCRIPTION: 'Введите свой электронный адрес, связанный с вашим аккаунтом',
    MAIL_SENDED: 'На адрес, связанный с вашим аккаунтом, было отправлено сообщение. Проверьте электронную почту, чтобы продолжить.',
    EMAIL_LABEL: 'Почта',
    EMAIL_PLACEHOLDER: 'Ваш электронный адрес',
    RESTORE: 'Восстановить аккаунт',
    SEND_MAIL: 'Далее',
    GO_TO_LOGIN: 'Войти в аккаунт',
    HEADER_TITLE: 'Смена пароля',
    RESET_HEADER_TITLE: 'Сброс пароля',
    CURRENT_PASSWORD_LABEL: 'Текущий пароль',
    CURRENT_PASSWORD_PLACEHOLDER: 'Ваше текущий пароль',
    NEW_PASSWORD_LABEL: 'Новый пароль',
    NEW_PASSWORD_PLACEHOLDER: 'Введите новый пароль',
    NEW_PASSWORD_CONFIRM_LABEL: 'Подтверждение пароля',
    NEW_PASSWORD_CONFIRM_PLACEHOLDER: 'Повторите пароль пожалуйста',
    FORGOT_PASSWORD: 'Забыли пароль?',
    CHANGE_PASSWORD_BTN: 'Сменить пароль',
    RESET_PASSWORD_BTN: 'Далее',
  },

  SETTINGS: {
    SUBMIT: 'Принять',
    CHANGE_LANGUAGE: 'Сменить язык',
  },

  EXIT: {
    TITLE: 'Выйти',
    SUBTITLE: 'Вы уверены, что хотите выйти?',
    CANCEL: 'Отмена',
    OK: 'Ок',
  },

  MODAL: {
    CANCEL: 'Отменить',
    SAVE: 'Сохранить',
    OK: 'Ок',
  },

  BOTTOM_TABS: {
    SEARCH: 'Поиск',
    ANKETA: 'Анкета',
    PROFILE: 'Профиль',
  },

  PROFILE: {
    HEADER_TITLE: 'Настройки профиля',
    CHANGE_NAME: 'Имя',
    CHANGE_EMAIL: 'Электронный адрес',
    CHANGE_PASSWORD: 'Пароль',
    CHANGE_LANGUAGE: 'Язык приложения',
    CHANGE_AGE: 'Возраст',
    CHANGE_DATE_BIRTH: 'Дата рождения',
    CHANGE_SEX: 'Пол',
    CHANGE_CITY: 'Город',
    MODAL_TITLE_NAME: 'Имя',
    MODAL_PLACEHOLDER_NAME: 'Ваше имя',
    MODAL_TITLE_EMAIL: 'Электронный адрес',
    MODAL_PLACEHOLDER_EMAIL: 'Ваш email',
    LOGOUT: 'Выйти',
  },

  ANKETA: {
    HEADER_TITLE: 'Моя анкета',
    SMOKING: 'Курение',
    RELIGION:'Религия',
    CHILDREN:'Hаличие детей',
    HAIR_COLOR: 'Цвет волос',
    EYE_COLOR:'Цвет глаз',
    ZODIAC:'Знак Зодиака',
    BODY_TYPE:'Телосложение',
    BODY_HEIGHT:'Рост',
    AGE:'Возраст',
    SOCIAL_STATUS:'Социальный статус',
    BAD_HABITS:'Отношение к вредным привычкам',
    WORK_TYPE:'Работаю в сфере',
    MONTHLY_INCOME:'Месячный доход долларов',
    HOBBIES:'Увлечения',
    MARRIAGE:'Отношение к браку',
    FUTURE_CHILDREN:'Желанность детей',
    POSSESSIONS:'Имущество',
    RESPONSIBILITY:'Обязанности',
    PLACE_WANT_LIVE:'Хочу жить в',
    LEISURE_ACTIVITIES:'Досуг',
    PRESENTS:'Подарки',
    HATES:'Категорически не приемлю',
  },

  BIRTHDAY: {
    HEADER_TITLE: 'Изменить дату рождения',
    SAVE_BTN: 'Сохранить',
  },
  CITY: {
    HEADER_TITLE: 'Изменить город',
    INPUT_PLACEHOLDER: 'Найти город',
  },
  MODAL_UNSAVED: {
    TITLE: 'Несохраненные изменения',
    DESCRIPTION: 'У вас есть несохраненные изменения. Отменить в любом случае?',
    OK_BTN: 'Да',
    NO_BTN: 'Нет',
  }
};
